In [1]:
import numpy as np

In [14]:
# Create an array
a = np.array([1, 2, 3])
b = np.array([[1, 2, 3],[4, 5, 6]])
c = np.ones((2,2)) #np.zeros, np.eye
d = np.random.random((2,2))

print(a.shape, b.shape)
print(c)
print(d)
print(a.dtype,b.dtype) #print data types

(3,) (2, 3)
[[1. 1.]
 [1. 1.]]
[[0.16588131 0.66522188]
 [0.19424474 0.55770322]]
int32 int32


In [13]:
# array index, starts from 0 instead of 1
print(b[1,:]) #print the second row
print(b[np.arange(2),[0,1]]) # print the selected elements
print(b[b>2]) #print elements >2

[4 5 6]
[1 5]
[3 4 5 6]


In [18]:
# Array operation
print (c*d) # +, -, /, np.sqrt(), elementwise multiplication
print (np.dot(c,d)) # products of vectors

print (np.sum(b,axis =0)) #sum along row
print (b.T) #transpose

[[0.16588131 0.66522188]
 [0.19424474 0.55770322]]
[[0.36012605 1.22292509]
 [0.36012605 1.22292509]]
[5 7 9]
[[1 4]
 [2 5]
 [3 6]]


In [29]:
# Broadcasting, which allows the operation between smaller-size array and larger-size array
e = np.array([1, 0, 1])
print (b+e)

ee = np.tile(e,(2,1)) # another option
print (b+ee)

#reshape)
print(b.dot(np.reshape(e,(3,1))))

[[2 2 4]
 [5 5 7]]
[[2 2 4]
 [5 5 7]]
[[ 4]
 [10]]
